export interface CanadianCity {
  slug: string;
  nameFr: string;
  nameEn: string;
  provinceCode: string;
  provinceSlug: string;
  provinceNameFr: string;
  provinceNameEn: string;
  taxNoteFr: string;
  taxNoteEn: string;
  descriptionFr: string;
  descriptionEn: string;
}

export const CANADIAN_CITIES: CanadianCity[] = [
  // Québec
  {
    slug: 'montreal',
    nameFr: 'Montréal',
    nameEn: 'Montreal',
    provinceCode: 'QC',
    provinceSlug: 'quebec',
    provinceNameFr: 'Québec',
    provinceNameEn: 'Quebec',
    taxNoteFr: 'TPS 5 % + TVQ 9,975 %',
    taxNoteEn: 'GST 5% + QST 9.975%',
    descriptionFr: 'Métropole économique du Québec, Montréal regroupe des milliers de PME et travailleurs autonomes. ComptaFlow offre une comptabilité en ligne adaptée aux réalités montréalaises.',
    descriptionEn: 'Montreal is Quebec\'s economic hub, home to thousands of SMBs and self-employed workers. ComptaFlow offers online accounting tailored to Montreal businesses.',
  },
  {
    slug: 'quebec-ville',
    nameFr: 'Québec (Ville)',
    nameEn: 'Quebec City',
    provinceCode: 'QC',
    provinceSlug: 'quebec',
    provinceNameFr: 'Québec',
    provinceNameEn: 'Quebec',
    taxNoteFr: 'TPS 5 % + TVQ 9,975 %',
    taxNoteEn: 'GST 5% + QST 9.975%',
    descriptionFr: 'Capitale nationale du Québec, la région de Québec compte de nombreux entrepreneurs en services professionnels. ComptaFlow assure votre conformité Loi 25 et TVQ.',
    descriptionEn: 'Quebec City is home to growing professional services firms. ComptaFlow handles your QST filings and Law 25 compliance remotely.',
  },
  {
    slug: 'laval',
    nameFr: 'Laval',
    nameEn: 'Laval',
    provinceCode: 'QC',
    provinceSlug: 'quebec',
    provinceNameFr: 'Québec',
    provinceNameEn: 'Quebec',
    taxNoteFr: 'TPS 5 % + TVQ 9,975 %',
    taxNoteEn: 'GST 5% + QST 9.975%',
    descriptionFr: 'Deuxième plus grande ville du Québec, Laval est un bassin important de PME dans la construction, le commerce de détail et les services. Gérez vos livres à distance avec ComptaFlow.',
    descriptionEn: 'Laval is a major SMB hub in Greater Montreal. Manage your books remotely with ComptaFlow.',
  },
  {
    slug: 'longueuil',
    nameFr: 'Longueuil',
    nameEn: 'Longueuil',
    provinceCode: 'QC',
    provinceSlug: 'quebec',
    provinceNameFr: 'Québec',
    provinceNameEn: 'Quebec',
    taxNoteFr: 'TPS 5 % + TVQ 9,975 %',
    taxNoteEn: 'GST 5% + QST 9.975%',
    descriptionFr: 'Sur la rive-sud de Montréal, les entrepreneurs de Longueuil bénéficient du même service comptable premium que dans les grandes villes, à distance.',
    descriptionEn: 'South Shore Montreal entrepreneurs get the same premium accounting service, remotely.',
  },
  {
    slug: 'sherbrooke',
    nameFr: 'Sherbrooke',
    nameEn: 'Sherbrooke',
    provinceCode: 'QC',
    provinceSlug: 'quebec',
    provinceNameFr: 'Québec',
    provinceNameEn: 'Quebec',
    taxNoteFr: 'TPS 5 % + TVQ 9,975 %',
    taxNoteEn: 'GST 5% + QST 9.975%',
    descriptionFr: 'Hub économique des Cantons-de-l\'Est, Sherbrooke accueille de nombreux entrepreneurs innovants. ComptaFlow vous accompagne pour vos déclarations TPS/TVQ et votre tenue de livres.',
    descriptionEn: 'Sherbrooke is a growing startup hub in Eastern Townships. ComptaFlow handles your GST/QST and bookkeeping online.',
  },
  {
    slug: 'gatineau',
    nameFr: 'Gatineau',
    nameEn: 'Gatineau',
    provinceCode: 'QC',
    provinceSlug: 'quebec',
    provinceNameFr: 'Québec',
    provinceNameEn: 'Quebec',
    taxNoteFr: 'TPS 5 % + TVQ 9,975 %',
    taxNoteEn: 'GST 5% + QST 9.975%',
    descriptionFr: 'À la frontière Ontario-Québec, les entrepreneurs de Gatineau font souvent face à des situations fiscales hybrides. ComptaFlow maîtrise les règles des deux provinces.',
    descriptionEn: 'On the Ontario-Quebec border, Gatineau entrepreneurs face hybrid tax situations. ComptaFlow handles both QST and HST.',
  },
  {
    slug: 'trois-rivieres',
    nameFr: 'Trois-Rivières',
    nameEn: 'Trois-Rivières',
    provinceCode: 'QC',
    provinceSlug: 'quebec',
    provinceNameFr: 'Québec',
    provinceNameEn: 'Quebec',
    taxNoteFr: 'TPS 5 % + TVQ 9,975 %',
    taxNoteEn: 'GST 5% + QST 9.975%',
    descriptionFr: 'Pôle économique important de la Mauricie, Trois-Rivières compte de nombreuses PME manufacturières et de services. ComptaFlow gère vos déclarations TPS/TVQ à distance.',
    descriptionEn: 'Trois-Rivières is a key economic hub in the Mauricie region, home to many manufacturing and service SMBs. ComptaFlow handles your GST/QST filings remotely.',
  },
  // Ontario
  {
    slug: 'toronto',
    nameFr: 'Toronto',
    nameEn: 'Toronto',
    provinceCode: 'ON',
    provinceSlug: 'ontario',
    provinceNameFr: 'Ontario',
    provinceNameEn: 'Ontario',
    taxNoteFr: 'TVH 13 %',
    taxNoteEn: 'HST 13%',
    descriptionFr: 'Plus grande métropole du Canada, Toronto concentre des dizaines de milliers de PME dans tous les secteurs. ComptaFlow offre la tenue de livres en ligne et les déclarations TVH pour entrepreneurs torontois.',
    descriptionEn: 'Canada\'s largest city, Toronto is home to tens of thousands of SMBs. ComptaFlow provides online bookkeeping and HST filings for Toronto entrepreneurs.',
  },
  {
    slug: 'ottawa',
    nameFr: 'Ottawa',
    nameEn: 'Ottawa',
    provinceCode: 'ON',
    provinceSlug: 'ontario',
    provinceNameFr: 'Ontario',
    provinceNameEn: 'Ontario',
    taxNoteFr: 'TVH 13 %',
    taxNoteEn: 'HST 13%',
    descriptionFr: 'Capitale fédérale, Ottawa accueille de nombreux consultants gouvernementaux et agences. ComptaFlow s\'occupe de vos livres et déclarations TVH pour que vous vous concentriez sur vos contrats.',
    descriptionEn: 'Ottawa\'s government consultants and agencies rely on ComptaFlow for bookkeeping and HST compliance.',
  },
  {
    slug: 'mississauga',
    nameFr: 'Mississauga',
    nameEn: 'Mississauga',
    provinceCode: 'ON',
    provinceSlug: 'ontario',
    provinceNameFr: 'Ontario',
    provinceNameEn: 'Ontario',
    taxNoteFr: 'TVH 13 %',
    taxNoteEn: 'HST 13%',
    descriptionFr: 'Mississauga est l\'une des villes canadiennes à plus forte croissance économique. ComptaFlow accompagne les PME locales avec tenue de livres, paie et TVH.',
    descriptionEn: 'Mississauga is one of Canada\'s fastest-growing business cities. ComptaFlow helps local SMBs with bookkeeping, payroll, and HST.',
  },
  {
    slug: 'brampton',
    nameFr: 'Brampton',
    nameEn: 'Brampton',
    provinceCode: 'ON',
    provinceSlug: 'ontario',
    provinceNameFr: 'Ontario',
    provinceNameEn: 'Ontario',
    taxNoteFr: 'TVH 13 %',
    taxNoteEn: 'HST 13%',
    descriptionFr: 'Brampton compte l\'une des plus fortes concentrations de PME en transport, logistique et commerce de détail au pays. ComptaFlow gère votre tenue de livres et vos remises TVH.',
    descriptionEn: 'Brampton has one of the country\'s highest concentrations of transport, logistics, and retail SMBs. ComptaFlow handles your bookkeeping and HST remittances.',
  },
  {
    slug: 'hamilton',
    nameFr: 'Hamilton',
    nameEn: 'Hamilton',
    provinceCode: 'ON',
    provinceSlug: 'ontario',
    provinceNameFr: 'Ontario',
    provinceNameEn: 'Ontario',
    taxNoteFr: 'TVH 13 %',
    taxNoteEn: 'HST 13%',
    descriptionFr: 'Ancienne ville industrielle en pleine transformation, Hamilton voit éclore de nombreuses PME manufacturières et créatives. ComptaFlow s\'occupe de vos livres et déclarations TVH.',
    descriptionEn: 'A former steel town now reinventing itself, Hamilton is home to a growing wave of manufacturing and creative SMBs. ComptaFlow handles your books and HST filings.',
  },
  {
    slug: 'kitchener',
    nameFr: 'Kitchener',
    nameEn: 'Kitchener',
    provinceCode: 'ON',
    provinceSlug: 'ontario',
    provinceNameFr: 'Ontario',
    provinceNameEn: 'Ontario',
    taxNoteFr: 'TVH 13 %',
    taxNoteEn: 'HST 13%',
    descriptionFr: 'Cœur technologique du « Silicon Valley du Nord », Kitchener attire startups et PME innovantes. ComptaFlow accompagne leur croissance avec une comptabilité 100 % en ligne.',
    descriptionEn: 'The heart of Canada\'s "Silicon Valley North," Kitchener attracts startups and innovative SMBs. ComptaFlow supports their growth with 100% online accounting.',
  },
  {
    slug: 'london',
    nameFr: 'London',
    nameEn: 'London',
    provinceCode: 'ON',
    provinceSlug: 'ontario',
    provinceNameFr: 'Ontario',
    provinceNameEn: 'Ontario',
    taxNoteFr: 'TVH 13 %',
    taxNoteEn: 'HST 13%',
    descriptionFr: 'London, Ontario, regroupe des PME diversifiées en santé, éducation et fabrication. ComptaFlow simplifie votre tenue de livres et vos remises TVH.',
    descriptionEn: 'London, Ontario is home to diverse SMBs in healthcare, education, and manufacturing. ComptaFlow simplifies your bookkeeping and HST remittances.',
  },
  {
    slug: 'windsor',
    nameFr: 'Windsor',
    nameEn: 'Windsor',
    provinceCode: 'ON',
    provinceSlug: 'ontario',
    provinceNameFr: 'Ontario',
    provinceNameEn: 'Ontario',
    taxNoteFr: 'TVH 13 %',
    taxNoteEn: 'HST 13%',
    descriptionFr: 'Frontalière des États-Unis, Windsor compte de nombreuses PME en commerce transfrontalier et manufacturier. ComptaFlow gère votre comptabilité et vos déclarations TVH.',
    descriptionEn: 'A border city facing the U.S., Windsor is home to many cross-border trade and manufacturing SMBs. ComptaFlow handles your accounting and HST filings.',
  },
  // British Columbia
  {
    slug: 'vancouver',
    nameFr: 'Vancouver',
    nameEn: 'Vancouver',
    provinceCode: 'BC',
    provinceSlug: 'colombie-britannique',
    provinceNameFr: 'Colombie-Britannique',
    provinceNameEn: 'British Columbia',
    taxNoteFr: 'TPS 5 % + TVP 7 %',
    taxNoteEn: 'GST 5% + PST 7%',
    descriptionFr: 'Vancouver attire des startups technologiques et des entrepreneurs créatifs du monde entier. ComptaFlow maîtrise les particularités fiscales BC (TPS + TVP) pour votre croissance.',
    descriptionEn: 'Vancouver\'s tech startup ecosystem and creative entrepreneurs rely on ComptaFlow for GST/PST compliance and online bookkeeping.',
  },
  {
    slug: 'victoria',
    nameFr: 'Victoria',
    nameEn: 'Victoria',
    provinceCode: 'BC',
    provinceSlug: 'colombie-britannique',
    provinceNameFr: 'Colombie-Britannique',
    provinceNameEn: 'British Columbia',
    taxNoteFr: 'TPS 5 % + TVP 7 %',
    taxNoteEn: 'GST 5% + PST 7%',
    descriptionFr: 'Victoria, capitale de la C.-B., abrite de nombreuses petites entreprises en tourisme, tech et services. Gérez vos finances à distance avec ComptaFlow.',
    descriptionEn: 'Victoria\'s tourism, tech, and service businesses manage their finances remotely with ComptaFlow.',
  },
  {
    slug: 'surrey',
    nameFr: 'Surrey',
    nameEn: 'Surrey',
    provinceCode: 'BC',
    provinceSlug: 'colombie-britannique',
    provinceNameFr: 'Colombie-Britannique',
    provinceNameEn: 'British Columbia',
    taxNoteFr: 'TPS 5 % + TVP 7 %',
    taxNoteEn: 'GST 5% + PST 7%',
    descriptionFr: 'Surrey est l\'une des villes à la croissance la plus rapide au Canada. Des milliers de petites entreprises y voient le jour chaque année — ComptaFlow les accompagne dès le départ.',
    descriptionEn: 'Surrey is one of Canada\'s fastest-growing cities. Thousands of new businesses launch here each year — ComptaFlow supports them from day one.',
  },
  {
    slug: 'burnaby',
    nameFr: 'Burnaby',
    nameEn: 'Burnaby',
    provinceCode: 'BC',
    provinceSlug: 'colombie-britannique',
    provinceNameFr: 'Colombie-Britannique',
    provinceNameEn: 'British Columbia',
    taxNoteFr: 'TPS 5 % + TVP 7 %',
    taxNoteEn: 'GST 5% + PST 7%',
    descriptionFr: 'Au cœur du Grand Vancouver, Burnaby accueille de nombreuses PME en commerce de détail et services professionnels. ComptaFlow gère vos déclarations TPS/TVP à distance.',
    descriptionEn: 'At the heart of Metro Vancouver, Burnaby is home to many retail and professional services SMBs. ComptaFlow handles your GST/PST filings remotely.',
  },
  {
    slug: 'richmond',
    nameFr: 'Richmond',
    nameEn: 'Richmond',
    provinceCode: 'BC',
    provinceSlug: 'colombie-britannique',
    provinceNameFr: 'Colombie-Britannique',
    provinceNameEn: 'British Columbia',
    taxNoteFr: 'TPS 5 % + TVP 7 %',
    taxNoteEn: 'GST 5% + PST 7%',
    descriptionFr: 'Richmond est un carrefour commercial international important du Grand Vancouver. ComptaFlow accompagne ses entrepreneurs avec une comptabilité en ligne sécurisée.',
    descriptionEn: 'Richmond is a major international trade hub in Metro Vancouver. ComptaFlow supports its entrepreneurs with secure online accounting.',
  },
  // Alberta
  {
    slug: 'calgary',
    nameFr: 'Calgary',
    nameEn: 'Calgary',
    provinceCode: 'AB',
    provinceSlug: 'alberta',
    provinceNameFr: 'Alberta',
    provinceNameEn: 'Alberta',
    taxNoteFr: 'TPS 5 % (Aucune taxe provinciale)',
    taxNoteEn: 'GST 5% (No provincial sales tax)',
    descriptionFr: 'Alberta n\'a pas de taxe de vente provinciale — un avantage fiscal pour les entreprises. ComptaFlow s\'occupe de vos obligations TPS fédérale et de votre comptabilité à Calgary.',
    descriptionEn: 'Alberta has no provincial sales tax — a competitive advantage. ComptaFlow handles federal GST and bookkeeping for Calgary businesses.',
  },
  {
    slug: 'edmonton',
    nameFr: 'Edmonton',
    nameEn: 'Edmonton',
    provinceCode: 'AB',
    provinceSlug: 'alberta',
    provinceNameFr: 'Alberta',
    provinceNameEn: 'Alberta',
    taxNoteFr: 'TPS 5 % (Aucune taxe provinciale)',
    taxNoteEn: 'GST 5% (No provincial sales tax)',
    descriptionFr: 'Capitale albertaine, Edmonton est un carrefour pour les industries pétrolières, technologiques et commerciales. ComptaFlow modernise votre comptabilité avec un portail client sécurisé.',
    descriptionEn: 'Edmonton is a hub for oil, tech, and trade industries. ComptaFlow modernizes your accounting with a secure client portal.',
  },
  {
    slug: 'red-deer',
    nameFr: 'Red Deer',
    nameEn: 'Red Deer',
    provinceCode: 'AB',
    provinceSlug: 'alberta',
    provinceNameFr: 'Alberta',
    provinceNameEn: 'Alberta',
    taxNoteFr: 'TPS 5 % (Aucune taxe provinciale)',
    taxNoteEn: 'GST 5% (No provincial sales tax)',
    descriptionFr: 'Entre Calgary et Edmonton, Red Deer est un centre agricole et manufacturier dynamique. ComptaFlow s\'occupe de vos obligations TPS fédérale et de votre comptabilité à distance.',
    descriptionEn: 'Located between Calgary and Edmonton, Red Deer is a dynamic agricultural and manufacturing hub. ComptaFlow handles federal GST and remote bookkeeping for local businesses.',
  },
  // Manitoba
  {
    slug: 'winnipeg',
    nameFr: 'Winnipeg',
    nameEn: 'Winnipeg',
    provinceCode: 'MB',
    provinceSlug: 'manitoba',
    provinceNameFr: 'Manitoba',
    provinceNameEn: 'Manitoba',
    taxNoteFr: 'TPS 5 % + TVP 7 %',
    taxNoteEn: 'GST 5% + PST 7%',
    descriptionFr: 'Winnipeg est le cœur économique des Prairies. ComptaFlow accompagne les PME de Winnipeg pour leurs obligations TPS/TVP et leur tenue de livres mensuelle.',
    descriptionEn: 'Winnipeg is the economic heart of the Prairies. ComptaFlow supports local SMBs with GST/PST compliance and monthly bookkeeping.',
  },
  // Nova Scotia
  {
    slug: 'halifax',
    nameFr: 'Halifax',
    nameEn: 'Halifax',
    provinceCode: 'NS',
    provinceSlug: 'nouvelle-ecosse',
    provinceNameFr: 'Nouvelle-Écosse',
    provinceNameEn: 'Nova Scotia',
    taxNoteFr: 'TVH 15 %',
    taxNoteEn: 'HST 15%',
    descriptionFr: 'Halifax est le pôle économique des Maritimes, avec un secteur tech et maritime en pleine croissance. ComptaFlow gère vos déclarations TVH et votre comptabilité en ligne.',
    descriptionEn: 'Halifax is the Maritimes\' economic hub, with a growing tech and maritime sector. ComptaFlow handles your HST filings and online accounting.',
  },
  // Saskatchewan
  {
    slug: 'saskatoon',
    nameFr: 'Saskatoon',
    nameEn: 'Saskatoon',
    provinceCode: 'SK',
    provinceSlug: 'saskatchewan',
    provinceNameFr: 'Saskatchewan',
    provinceNameEn: 'Saskatchewan',
    taxNoteFr: 'TPS 5 % + TVP 6 %',
    taxNoteEn: 'GST 5% + PST 6%',
    descriptionFr: 'Saskatoon est un centre d\'innovation pour les industries agricole et minière. ComptaFlow accompagne les entrepreneurs de la Saskatchewan avec tenue de livres et déclarations TPS/TVP.',
    descriptionEn: 'Saskatoon is an innovation hub for agriculture and mining. ComptaFlow supports Saskatchewan entrepreneurs with bookkeeping and GST/PST filings.',
  },
  {
    slug: 'regina',
    nameFr: 'Regina',
    nameEn: 'Regina',
    provinceCode: 'SK',
    provinceSlug: 'saskatchewan',
    provinceNameFr: 'Saskatchewan',
    provinceNameEn: 'Saskatchewan',
    taxNoteFr: 'TPS 5 % + TVP 6 %',
    taxNoteEn: 'GST 5% + PST 6%',
    descriptionFr: 'Capitale de la Saskatchewan, Regina compte de nombreuses PME dans les secteurs pétrolier, agricole et gouvernemental. Gérez vos finances à distance avec ComptaFlow.',
    descriptionEn: 'Regina\'s oil, agriculture, and government sector SMBs manage their finances remotely with ComptaFlow.',
  },
  // New Brunswick
  {
    slug: 'moncton',
    nameFr: 'Moncton',
    nameEn: 'Moncton',
    provinceCode: 'NB',
    provinceSlug: 'nouveau-brunswick',
    provinceNameFr: 'Nouveau-Brunswick',
    provinceNameEn: 'New Brunswick',
    taxNoteFr: 'TVH 15 %',
    taxNoteEn: 'HST 15%',
    descriptionFr: 'Moncton est le moteur économique du Nouveau-Brunswick, avec un secteur logistique et bilingue florissant. ComptaFlow gère vos déclarations TVH et votre comptabilité en ligne.',
    descriptionEn: 'Moncton is New Brunswick\'s economic engine, with a thriving bilingual logistics sector. ComptaFlow handles your HST filings and online accounting.',
  },
  // Prince Edward Island
  {
    slug: 'charlottetown',
    nameFr: 'Charlottetown',
    nameEn: 'Charlottetown',
    provinceCode: 'PE',
    provinceSlug: 'ipe',
    provinceNameFr: 'Île-du-Prince-Édouard',
    provinceNameEn: 'Prince Edward Island',
    taxNoteFr: 'TVH 15 %',
    taxNoteEn: 'HST 15%',
    descriptionFr: 'Capitale de l\'Île-du-Prince-Édouard, Charlottetown regroupe des PME en tourisme, agroalimentaire et services. ComptaFlow s\'occupe de vos déclarations TVH à distance.',
    descriptionEn: 'Prince Edward Island\'s capital, Charlottetown is home to SMBs in tourism, agri-food, and services. ComptaFlow handles your HST filings remotely.',
  },
  // Newfoundland and Labrador
  {
    slug: 'st-johns',
    nameFr: 'St. John\'s',
    nameEn: 'St. John\'s',
    provinceCode: 'NL',
    provinceSlug: 'terre-neuve',
    provinceNameFr: 'Terre-Neuve-et-Labrador',
    provinceNameEn: 'Newfoundland and Labrador',
    taxNoteFr: 'TVH 15 %',
    taxNoteEn: 'HST 15%',
    descriptionFr: 'St. John\'s est le centre économique de Terre-Neuve-et-Labrador, porté par l\'énergie et les pêcheries. ComptaFlow accompagne ses entrepreneurs avec une comptabilité 100 % en ligne.',
    descriptionEn: 'St. John\'s is Newfoundland and Labrador\'s economic hub, driven by energy and fisheries. ComptaFlow supports local entrepreneurs with 100% online accounting.',
  },
  // Yukon
  {
    slug: 'whitehorse',
    nameFr: 'Whitehorse',
    nameEn: 'Whitehorse',
    provinceCode: 'YT',
    provinceSlug: 'yukon',
    provinceNameFr: 'Yukon',
    provinceNameEn: 'Yukon',
    taxNoteFr: 'TPS 5 %',
    taxNoteEn: 'GST 5%',
    descriptionFr: 'Capitale du Yukon, Whitehorse n\'a aucune taxe de vente territoriale — un avantage pour ses PME en tourisme et ressources naturelles. ComptaFlow gère votre TPS fédérale à distance.',
    descriptionEn: 'Yukon\'s capital, Whitehorse has no territorial sales tax — an advantage for its tourism and natural resources SMBs. ComptaFlow handles your federal GST remotely.',
  },
  // Northwest Territories
  {
    slug: 'yellowknife',
    nameFr: 'Yellowknife',
    nameEn: 'Yellowknife',
    provinceCode: 'NT',
    provinceSlug: 'tno',
    provinceNameFr: 'Territoires du Nord-Ouest',
    provinceNameEn: 'Northwest Territories',
    taxNoteFr: 'TPS 5 %',
    taxNoteEn: 'GST 5%',
    descriptionFr: 'Yellowknife est le cœur économique des Territoires du Nord-Ouest, porté par l\'exploitation minière et le secteur public. ComptaFlow offre une comptabilité en ligne adaptée, où que vous soyez.',
    descriptionEn: 'Yellowknife is the economic heart of the Northwest Territories, driven by mining and the public sector. ComptaFlow offers tailored online accounting, wherever you are.',
  },
  // Nunavut
  {
    slug: 'iqaluit',
    nameFr: 'Iqaluit',
    nameEn: 'Iqaluit',
    provinceCode: 'NU',
    provinceSlug: 'nunavut',
    provinceNameFr: 'Nunavut',
    provinceNameEn: 'Nunavut',
    taxNoteFr: 'TPS 5 %',
    taxNoteEn: 'GST 5%',
    descriptionFr: 'Capitale du Nunavut, Iqaluit accueille des PME et organismes communautaires qui méritent un accès comptable de qualité, peu importe la distance. ComptaFlow dessert tout le territoire en ligne.',
    descriptionEn: 'Nunavut\'s capital, Iqaluit is home to SMBs and community organizations that deserve quality accounting access regardless of distance. ComptaFlow serves the whole territory online.',
  },
];

export function getCity(slug: string): CanadianCity | undefined {
  return CANADIAN_CITIES.find((c) => c.slug === slug);
}

export function getCitiesByProvince(provinceCode: string): CanadianCity[] {
  return CANADIAN_CITIES.filter((c) => c.provinceCode === provinceCode);
}
