export interface CanadianCity {
  slug: string;
  nameFr: string;
  nameEn: string;
  provinceCode: string;
  provinceSlug: string;
  provinceNameFr: string;
  provinceNameEn: string;
  taxNoteFr: string;
  taxNoteEn: string;
  descriptionFr: string;
  descriptionEn: string;
}

export const CANADIAN_CITIES: CanadianCity[] = [
  // Québec
  {
    slug: 'montreal',
    nameFr: 'Montréal',
    nameEn: 'Montreal',
    provinceCode: 'QC',
    provinceSlug: 'quebec',
    provinceNameFr: 'Québec',
    provinceNameEn: 'Quebec',
    taxNoteFr: 'TPS 5 % + TVQ 9,975 %',
    taxNoteEn: 'GST 5% + QST 9.975%',
    descriptionFr: 'Métropole économique du Québec, Montréal regroupe des milliers de PME et travailleurs autonomes. ComptaFlow offre une comptabilité en ligne adaptée aux réalités montréalaises.',
    descriptionEn: 'Montreal is Quebec\'s economic hub, home to thousands of SMBs and self-employed workers. ComptaFlow offers online accounting tailored to Montreal businesses.',
  },
  {
    slug: 'quebec-ville',
    nameFr: 'Québec (Ville)',
    nameEn: 'Quebec City',
    provinceCode: 'QC',
    provinceSlug: 'quebec',
    provinceNameFr: 'Québec',
    provinceNameEn: 'Quebec',
    taxNoteFr: 'TPS 5 % + TVQ 9,975 %',
    taxNoteEn: 'GST 5% + QST 9.975%',
    descriptionFr: 'Capitale nationale du Québec, la région de Québec compte de nombreux entrepreneurs en services professionnels. ComptaFlow assure votre conformité Loi 25 et TVQ.',
    descriptionEn: 'Quebec City is home to growing professional services firms. ComptaFlow handles your QST filings and Law 25 compliance remotely.',
  },
  {
    slug: 'laval',
    nameFr: 'Laval',
    nameEn: 'Laval',
    provinceCode: 'QC',
    provinceSlug: 'quebec',
    provinceNameFr: 'Québec',
    provinceNameEn: 'Quebec',
    taxNoteFr: 'TPS 5 % + TVQ 9,975 %',
    taxNoteEn: 'GST 5% + QST 9.975%',
    descriptionFr: 'Deuxième plus grande ville du Québec, Laval est un bassin important de PME dans la construction, le commerce de détail et les services. Gérez vos livres à distance avec ComptaFlow.',
    descriptionEn: 'Laval is a major SMB hub in Greater Montreal. Manage your books remotely with ComptaFlow.',
  },
  {
    slug: 'longueuil',
    nameFr: 'Longueuil',
    nameEn: 'Longueuil',
    provinceCode: 'QC',
    provinceSlug: 'quebec',
    provinceNameFr: 'Québec',
    provinceNameEn: 'Quebec',
    taxNoteFr: 'TPS 5 % + TVQ 9,975 %',
    taxNoteEn: 'GST 5% + QST 9.975%',
    descriptionFr: 'Sur la rive-sud de Montréal, les entrepreneurs de Longueuil bénéficient du même service comptable premium que dans les grandes villes, à distance.',
    descriptionEn: 'South Shore Montreal entrepreneurs get the same premium accounting service, remotely.',
  },
  {
    slug: 'sherbrooke',
    nameFr: 'Sherbrooke',
    nameEn: 'Sherbrooke',
    provinceCode: 'QC',
    provinceSlug: 'quebec',
    provinceNameFr: 'Québec',
    provinceNameEn: 'Quebec',
    taxNoteFr: 'TPS 5 % + TVQ 9,975 %',
    taxNoteEn: 'GST 5% + QST 9.975%',
    descriptionFr: 'Hub économique des Cantons-de-l\'Est, Sherbrooke accueille de nombreux entrepreneurs innovants. ComptaFlow vous accompagne pour vos déclarations TPS/TVQ et votre tenue de livres.',
    descriptionEn: 'Sherbrooke is a growing startup hub in Eastern Townships. ComptaFlow handles your GST/QST and bookkeeping online.',
  },
  {
    slug: 'gatineau',
    nameFr: 'Gatineau',
    nameEn: 'Gatineau',
    provinceCode: 'QC',
    provinceSlug: 'quebec',
    provinceNameFr: 'Québec',
    provinceNameEn: 'Quebec',
    taxNoteFr: 'TPS 5 % + TVQ 9,975 %',
    taxNoteEn: 'GST 5% + QST 9.975%',
    descriptionFr: 'À la frontière Ontario-Québec, les entrepreneurs de Gatineau font souvent face à des situations fiscales hybrides. ComptaFlow maîtrise les règles des deux provinces.',
    descriptionEn: 'On the Ontario-Quebec border, Gatineau entrepreneurs face hybrid tax situations. ComptaFlow handles both QST and HST.',
  },
  // Ontario
  {
    slug: 'toronto',
    nameFr: 'Toronto',
    nameEn: 'Toronto',
    provinceCode: 'ON',
    provinceSlug: 'ontario',
    provinceNameFr: 'Ontario',
    provinceNameEn: 'Ontario',
    taxNoteFr: 'TVH 13 %',
    taxNoteEn: 'HST 13%',
    descriptionFr: 'Plus grande métropole du Canada, Toronto concentre des dizaines de milliers de PME dans tous les secteurs. ComptaFlow offre la tenue de livres en ligne et les déclarations TVH pour entrepreneurs torontois.',
    descriptionEn: 'Canada\'s largest city, Toronto is home to tens of thousands of SMBs. ComptaFlow provides online bookkeeping and HST filings for Toronto entrepreneurs.',
  },
  {
    slug: 'ottawa',
    nameFr: 'Ottawa',
    nameEn: 'Ottawa',
    provinceCode: 'ON',
    provinceSlug: 'ontario',
    provinceNameFr: 'Ontario',
    provinceNameEn: 'Ontario',
    taxNoteFr: 'TVH 13 %',
    taxNoteEn: 'HST 13%',
    descriptionFr: 'Capitale fédérale, Ottawa accueille de nombreux consultants gouvernementaux et agences. ComptaFlow s\'occupe de vos livres et déclarations TVH pour que vous vous concentriez sur vos contrats.',
    descriptionEn: 'Ottawa\'s government consultants and agencies rely on ComptaFlow for bookkeeping and HST compliance.',
  },
  {
    slug: 'mississauga',
    nameFr: 'Mississauga',
    nameEn: 'Mississauga',
    provinceCode: 'ON',
    provinceSlug: 'ontario',
    provinceNameFr: 'Ontario',
    provinceNameEn: 'Ontario',
    taxNoteFr: 'TVH 13 %',
    taxNoteEn: 'HST 13%',
    descriptionFr: 'Mississauga est l\'une des villes canadiennes à plus forte croissance économique. ComptaFlow accompagne les PME locales avec tenue de livres, paie et TVH.',
    descriptionEn: 'Mississauga is one of Canada\'s fastest-growing business cities. ComptaFlow helps local SMBs with bookkeeping, payroll, and HST.',
  },
  // British Columbia
  {
    slug: 'vancouver',
    nameFr: 'Vancouver',
    nameEn: 'Vancouver',
    provinceCode: 'BC',
    provinceSlug: 'colombie-britannique',
    provinceNameFr: 'Colombie-Britannique',
    provinceNameEn: 'British Columbia',
    taxNoteFr: 'TPS 5 % + TVP 7 %',
    taxNoteEn: 'GST 5% + PST 7%',
    descriptionFr: 'Vancouver attire des startups technologiques et des entrepreneurs créatifs du monde entier. ComptaFlow maîtrise les particularités fiscales BC (TPS + TVP) pour votre croissance.',
    descriptionEn: 'Vancouver\'s tech startup ecosystem and creative entrepreneurs rely on ComptaFlow for GST/PST compliance and online bookkeeping.',
  },
  {
    slug: 'victoria',
    nameFr: 'Victoria',
    nameEn: 'Victoria',
    provinceCode: 'BC',
    provinceSlug: 'colombie-britannique',
    provinceNameFr: 'Colombie-Britannique',
    provinceNameEn: 'British Columbia',
    taxNoteFr: 'TPS 5 % + TVP 7 %',
    taxNoteEn: 'GST 5% + PST 7%',
    descriptionFr: 'Victoria, capitale de la C.-B., abrite de nombreuses petites entreprises en tourisme, tech et services. Gérez vos finances à distance avec ComptaFlow.',
    descriptionEn: 'Victoria\'s tourism, tech, and service businesses manage their finances remotely with ComptaFlow.',
  },
  {
    slug: 'surrey',
    nameFr: 'Surrey',
    nameEn: 'Surrey',
    provinceCode: 'BC',
    provinceSlug: 'colombie-britannique',
    provinceNameFr: 'Colombie-Britannique',
    provinceNameEn: 'British Columbia',
    taxNoteFr: 'TPS 5 % + TVP 7 %',
    taxNoteEn: 'GST 5% + PST 7%',
    descriptionFr: 'Surrey est l\'une des villes à la croissance la plus rapide au Canada. Des milliers de petites entreprises y voient le jour chaque année — ComptaFlow les accompagne dès le départ.',
    descriptionEn: 'Surrey is one of Canada\'s fastest-growing cities. Thousands of new businesses launch here each year — ComptaFlow supports them from day one.',
  },
  // Alberta
  {
    slug: 'calgary',
    nameFr: 'Calgary',
    nameEn: 'Calgary',
    provinceCode: 'AB',
    provinceSlug: 'alberta',
    provinceNameFr: 'Alberta',
    provinceNameEn: 'Alberta',
    taxNoteFr: 'TPS 5 % (Aucune taxe provinciale)',
    taxNoteEn: 'GST 5% (No provincial sales tax)',
    descriptionFr: 'Alberta n\'a pas de taxe de vente provinciale — un avantage fiscal pour les entreprises. ComptaFlow s\'occupe de vos obligations TPS fédérale et de votre comptabilité à Calgary.',
    descriptionEn: 'Alberta has no provincial sales tax — a competitive advantage. ComptaFlow handles federal GST and bookkeeping for Calgary businesses.',
  },
  {
    slug: 'edmonton',
    nameFr: 'Edmonton',
    nameEn: 'Edmonton',
    provinceCode: 'AB',
    provinceSlug: 'alberta',
    provinceNameFr: 'Alberta',
    provinceNameEn: 'Alberta',
    taxNoteFr: 'TPS 5 % (Aucune taxe provinciale)',
    taxNoteEn: 'GST 5% (No provincial sales tax)',
    descriptionFr: 'Capitale albertaine, Edmonton est un carrefour pour les industries pétrolières, technologiques et commerciales. ComptaFlow modernise votre comptabilité avec un portail client sécurisé.',
    descriptionEn: 'Edmonton is a hub for oil, tech, and trade industries. ComptaFlow modernizes your accounting with a secure client portal.',
  },
  // Manitoba
  {
    slug: 'winnipeg',
    nameFr: 'Winnipeg',
    nameEn: 'Winnipeg',
    provinceCode: 'MB',
    provinceSlug: 'manitoba',
    provinceNameFr: 'Manitoba',
    provinceNameEn: 'Manitoba',
    taxNoteFr: 'TPS 5 % + TVP 7 %',
    taxNoteEn: 'GST 5% + PST 7%',
    descriptionFr: 'Winnipeg est le cœur économique des Prairies. ComptaFlow accompagne les PME de Winnipeg pour leurs obligations TPS/TVP et leur tenue de livres mensuelle.',
    descriptionEn: 'Winnipeg is the economic heart of the Prairies. ComptaFlow supports local SMBs with GST/PST compliance and monthly bookkeeping.',
  },
  // Nova Scotia
  {
    slug: 'halifax',
    nameFr: 'Halifax',
    nameEn: 'Halifax',
    provinceCode: 'NS',
    provinceSlug: 'nouvelle-ecosse',
    provinceNameFr: 'Nouvelle-Écosse',
    provinceNameEn: 'Nova Scotia',
    taxNoteFr: 'TVH 15 %',
    taxNoteEn: 'HST 15%',
    descriptionFr: 'Halifax est le pôle économique des Maritimes, avec un secteur tech et maritime en pleine croissance. ComptaFlow gère vos déclarations TVH et votre comptabilité en ligne.',
    descriptionEn: 'Halifax is the Maritimes\' economic hub, with a growing tech and maritime sector. ComptaFlow handles your HST filings and online accounting.',
  },
  // Saskatchewan
  {
    slug: 'saskatoon',
    nameFr: 'Saskatoon',
    nameEn: 'Saskatoon',
    provinceCode: 'SK',
    provinceSlug: 'saskatchewan',
    provinceNameFr: 'Saskatchewan',
    provinceNameEn: 'Saskatchewan',
    taxNoteFr: 'TPS 5 % + TVP 6 %',
    taxNoteEn: 'GST 5% + PST 6%',
    descriptionFr: 'Saskatoon est un centre d\'innovation pour les industries agricole et minière. ComptaFlow accompagne les entrepreneurs de la Saskatchewan avec tenue de livres et déclarations TPS/TVP.',
    descriptionEn: 'Saskatoon is an innovation hub for agriculture and mining. ComptaFlow supports Saskatchewan entrepreneurs with bookkeeping and GST/PST filings.',
  },
  {
    slug: 'regina',
    nameFr: 'Regina',
    nameEn: 'Regina',
    provinceCode: 'SK',
    provinceSlug: 'saskatchewan',
    provinceNameFr: 'Saskatchewan',
    provinceNameEn: 'Saskatchewan',
    taxNoteFr: 'TPS 5 % + TVP 6 %',
    taxNoteEn: 'GST 5% + PST 6%',
    descriptionFr: 'Capitale de la Saskatchewan, Regina compte de nombreuses PME dans les secteurs pétrolier, agricole et gouvernemental. Gérez vos finances à distance avec ComptaFlow.',
    descriptionEn: 'Regina\'s oil, agriculture, and government sector SMBs manage their finances remotely with ComptaFlow.',
  },
];

export function getCity(slug: string): CanadianCity | undefined {
  return CANADIAN_CITIES.find((c) => c.slug === slug);
}

export function getCitiesByProvince(provinceCode: string): CanadianCity[] {
  return CANADIAN_CITIES.filter((c) => c.provinceCode === provinceCode);
}
