export const destinations = [
  {
    id: 1,
    name: "Bali, Indonésie",
    image: "https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=600&q=80",
    price: 899,
    originalPrice: 1299,
    rating: 4.9,
    reviews: 2847,
    tag: "Tendance",
    tagColor: "bg-violet-500",
    duration: "7 nuits",
    includes: ["Vols", "Hôtel 5★", "Transferts"],
    discount: 31,
    availability: 3,
    category: "plage",
    country: "ID",
    emoji: "🌴",
  },
  {
    id: 2,
    name: "Paris, France",
    image: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=600&q=80",
    price: 649,
    originalPrice: 899,
    rating: 4.8,
    reviews: 5234,
    tag: "Best-seller",
    tagColor: "bg-amber-500",
    duration: "5 nuits",
    includes: ["Vols", "Hôtel 4★", "Petit-déj"],
    discount: 28,
    availability: 7,
    category: "culture",
    country: "FR",
    emoji: "🗼",
  },
  {
    id: 3,
    name: "Cancún, Mexique",
    image: "https://images.unsplash.com/photo-1552074284-5e88ef1aef18?w=600&q=80",
    price: 1099,
    originalPrice: 1599,
    rating: 4.7,
    reviews: 3102,
    tag: "Flash -31%",
    tagColor: "bg-red-500",
    duration: "10 nuits",
    includes: ["Vols", "All-inclusive", "Spa"],
    discount: 31,
    availability: 2,
    category: "plage",
    country: "MX",
    emoji: "🌊",
  },
  {
    id: 4,
    name: "Tokyo, Japon",
    image: "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=600&q=80",
    price: 1249,
    originalPrice: 1749,
    rating: 4.9,
    reviews: 1876,
    tag: "Exclusif",
    tagColor: "bg-blue-500",
    duration: "8 nuits",
    includes: ["Vols", "Hôtel 5★", "Guide"],
    discount: 29,
    availability: 5,
    category: "culture",
    country: "JP",
    emoji: "🌸",
  },
  {
    id: 5,
    name: "Santorin, Grèce",
    image: "https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?w=600&q=80",
    price: 799,
    originalPrice: 1099,
    rating: 4.8,
    reviews: 4521,
    tag: "Romantique",
    tagColor: "bg-pink-500",
    duration: "6 nuits",
    includes: ["Vols", "Hôtel vue mer", "Dîner"],
    discount: 27,
    availability: 4,
    category: "plage",
    country: "GR",
    emoji: "🏛️",
  },
  {
    id: 6,
    name: "Dubai, EAU",
    image: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=600&q=80",
    price: 1399,
    originalPrice: 1899,
    rating: 4.7,
    reviews: 2953,
    tag: "Luxe",
    tagColor: "bg-yellow-500",
    duration: "7 nuits",
    includes: ["Vols", "Hôtel 7★", "Excursions"],
    discount: 26,
    availability: 8,
    category: "luxe",
    country: "AE",
    emoji: "🏙️",
  },
];

export const flashDeals = [
  {
    id: 1,
    route: "Montréal → Miami",
    airline: "Air Canada",
    price: 189,
    originalPrice: 389,
    departure: "2026-07-15",
    duration: "3h 20m",
    seats: 4,
    class: "Économique",
    logo: "✈️",
    expiresIn: 7200,
  },
  {
    id: 2,
    route: "Toronto → Cancún",
    airline: "Sunwing",
    price: 299,
    originalPrice: 599,
    departure: "2026-08-03",
    duration: "4h 45m",
    seats: 2,
    class: "Tout inclus",
    logo: "🌅",
    expiresIn: 3600,
  },
  {
    id: 3,
    route: "Montréal → Paris",
    airline: "Air Transat",
    price: 449,
    originalPrice: 799,
    departure: "2026-09-12",
    duration: "7h 15m",
    seats: 6,
    class: "Premium",
    logo: "🗼",
    expiresIn: 14400,
  },
  {
    id: 4,
    route: "Vancouver → Tokyo",
    airline: "Japan Airlines",
    price: 699,
    originalPrice: 1299,
    departure: "2026-10-05",
    duration: "10h 30m",
    seats: 3,
    class: "Business",
    logo: "🌸",
    expiresIn: 5400,
  },
];

export const testimonials = [
  {
    id: 1,
    name: "Marie Tremblay",
    avatar: "MT",
    location: "Montréal, QC",
    rating: 5,
    text: "J'ai économisé plus de 600$ sur mon voyage à Bali. Le moteur de recherche trouve vraiment les meilleures offres en temps réel. Je recommande à 100%!",
    trip: "Bali 2025",
    savings: 612,
  },
  {
    id: 2,
    name: "Jean-Luc Beaumont",
    avatar: "JB",
    location: "Québec, QC",
    rating: 5,
    text: "Le portail client est incroyablement simple. J'ai réservé mon voyage à Tokyo en moins de 5 minutes. Les alertes de prix sont une fonctionnalité révolutionnaire.",
    trip: "Tokyo 2025",
    savings: 487,
  },
  {
    id: 3,
    name: "Sophie Laurent",
    avatar: "SL",
    location: "Ottawa, ON",
    rating: 5,
    text: "Enfin une plateforme qui comprend les voyageurs canadiens. Prix en CAD, service en français, offres exclusives. Mon voyage à Paris était parfait!",
    trip: "Paris 2026",
    savings: 341,
  },
];

export const stats = [
  { label: "Voyageurs satisfaits", value: "247K+", icon: "👥" },
  { label: "Destinations", value: "180+", icon: "🌍" },
  { label: "Économies moyennes", value: "38%", icon: "💰" },
  { label: "Offres analysées/jour", value: "2.4M+", icon: "🔍" },
];

export const features = [
  {
    icon: "🤖",
    title: "IA de Recherche",
    description: "Notre IA analyse 2,4 millions d'offres en temps réel pour trouver le meilleur prix garanti pour votre voyage.",
    highlight: "Prix Garanti Bas",
  },
  {
    icon: "🔔",
    title: "Alertes Prix",
    description: "Recevez une notification instantanée dès que le prix de votre destination préférée baisse. Ne ratez plus jamais une bonne affaire.",
    highlight: "Notifications Instant.",
  },
  {
    icon: "🌟",
    title: "Points Voyageur",
    description: "Gagnez des points à chaque réservation et échangez-les contre des réductions, surclassements ou voyages gratuits.",
    highlight: "Programme Fidélité",
  },
  {
    icon: "🛡️",
    title: "Réservation Sécurisée",
    description: "Annulation gratuite jusqu'à 48h avant le départ. Protection contre les imprévus incluse sur toutes les réservations.",
    highlight: "Remboursement Garanti",
  },
  {
    icon: "🗓️",
    title: "Planificateur IA",
    description: "Décrivez votre voyage idéal et notre IA génère un itinéraire complet, personnalisé et optimisé pour votre budget.",
    highlight: "Itinéraire Personnalisé",
  },
  {
    icon: "📱",
    title: "App Mobile",
    description: "Gérez vos voyages, billets et documents depuis votre téléphone. Check-in en ligne, cartes d'embarquement digitales.",
    highlight: "Disponible iOS & Android",
  },
];

export const popularSearches = [
  "Bali tout inclus",
  "Paris romantique",
  "Mexique plage",
  "Cuba winter getaway",
  "Tokyo cherry blossom",
  "Dubai luxe",
  "Grèce îles",
  "Floride famille",
];

export const airlines = [
  "Air Canada", "WestJet", "Air Transat", "Sunwing",
  "Porter Airlines", "Corsair", "Corsair", "Delta",
];

export const categories = [
  { id: "all", label: "Toutes", icon: "🌍" },
  { id: "plage", label: "Plage", icon: "🏖️" },
  { id: "culture", label: "Culture", icon: "🏛️" },
  { id: "luxe", label: "Luxe", icon: "💎" },
  { id: "aventure", label: "Aventure", icon: "🏔️" },
  { id: "famille", label: "Famille", icon: "👨‍👩‍👧" },
];

export const liveSearchSuggestions = [
  { query: "Cancún", type: "ville", country: "Mexique", deals: 47 },
  { query: "Barcelone", type: "ville", country: "Espagne", deals: 32 },
  { query: "Thaïlande", type: "pays", country: "Thaïlande", deals: 89 },
  { query: "Floride", type: "région", country: "USA", deals: 124 },
  { query: "Cuba", type: "pays", country: "Cuba", deals: 56 },
  { query: "Maroc", type: "pays", country: "Maroc", deals: 23 },
  { query: "Maldives", type: "archipel", country: "Maldives", deals: 15 },
  { query: "Jamaïque", type: "île", country: "Jamaïque", deals: 38 },
];
